POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "name": "Jhonny",
    "email": "jhonny@hotmail.com",
    "password": "123456",
    "role": "NORMAl"
}

###
# @name login
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "edson_magnini@hotmail.com",
    "password": "123456"
}

###
POST http://localhost:3000/band/create
Content-Type: application/json
Authorization: {{login.response.body.token}}

{
    "name": "Metallica",
    "musicGenre": "Rock",
    "responsible": "Rossi"
}

###
GET http://localhost:3000/band?bandName=Metallica 
Content-Type: application/json

###
POST http://localhost:3000/show/create
Content-Type: application/json

{
    "weekDay": "SEXTA",
    "startTime": 12,
    "endTime": 15,
    "bandId": "0958f621-5b67-41c1-aacd-ab6ae09d8376"
}

###
GET http://localhost:3000/show/info
Content-Type: application/json

{
    "weekDay": "SEXTA"
}

###
POST  http://localhost:3000/ticket/create
Content-Type: application/json
Authorization: {{login.response.body.token}}

{
    "name": "Show de sexta",
    "quantity": 200,
    "showId": "6feea15e-44d2-4704-a8f9-2c94e43533e8"
}

###
POST  http://localhost:3000/ticket/sell
Content-Type: application/json

{
    "id": "3e3d0df8-4bcb-4cde-b430-ac4c2542b6ff",
    "quantity": 2
}

